/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppTemplatesRouteImport } from './routes/_app.templates'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as AppProjectsIdRouteImport } from './routes/_app.projects.$id'
import { Route as AppProjectsBaruRouteImport } from './routes/_app.projects.baru'
import { Route as AppSettingsAiRouteImport } from './routes/_app.settings.ai'
import { Route as AppSettingsBahasaRouteImport } from './routes/_app.settings.bahasa'
import { Route as AppSettingsNotifikasiRouteImport } from './routes/_app.settings.notifikasi'
import { Route as AppSettingsProfilRouteImport } from './routes/_app.settings.profil'
import { Route as AppSettingsShortcutRouteImport } from './routes/_app.settings.shortcut'
import { Route as AppSettingsTampilanRouteImport } from './routes/_app.settings.tampilan'
import { Route as AppProjectsIdApiRouteImport } from './routes/_app.projects.$id.api'
import { Route as AppProjectsIdArchitectureRouteImport } from './routes/_app.projects.$id.architecture'
import { Route as AppProjectsIdCanvasRouteImport } from './routes/_app.projects.$id.canvas'
import { Route as AppProjectsIdDatabaseRouteImport } from './routes/_app.projects.$id.database'
import { Route as AppProjectsIdExportRouteImport } from './routes/_app.projects.$id.export'
import { Route as AppProjectsIdHistoryRouteImport } from './routes/_app.projects.$id.history'
import { Route as AppProjectsIdInterviewRouteImport } from './routes/_app.projects.$id.interview'
import { Route as AppProjectsIdOverviewRouteImport } from './routes/_app.projects.$id.overview'
import { Route as AppProjectsIdPrdRouteImport } from './routes/_app.projects.$id.prd'
import { Route as AppProjectsIdPromptsRouteImport } from './routes/_app.projects.$id.prompts'
import { Route as AppProjectsIdTasksRouteImport } from './routes/_app.projects.$id.tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsBaruRoute = AppProjectsBaruRouteImport.update({
  id: '/projects/baru',
  path: '/projects/baru',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAiRoute = AppSettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBahasaRoute = AppSettingsBahasaRouteImport.update({
  id: '/bahasa',
  path: '/bahasa',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsNotifikasiRoute = AppSettingsNotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsProfilRoute = AppSettingsProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsShortcutRoute = AppSettingsShortcutRouteImport.update({
  id: '/shortcut',
  path: '/shortcut',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsTampilanRoute = AppSettingsTampilanRouteImport.update({
  id: '/tampilan',
  path: '/tampilan',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppProjectsIdApiRoute = AppProjectsIdApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdArchitectureRoute =
  AppProjectsIdArchitectureRouteImport.update({
    id: '/architecture',
    path: '/architecture',
    getParentRoute: () => AppProjectsIdRoute,
  } as any)
const AppProjectsIdCanvasRoute = AppProjectsIdCanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdDatabaseRoute = AppProjectsIdDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdExportRoute = AppProjectsIdExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdHistoryRoute = AppProjectsIdHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdInterviewRoute = AppProjectsIdInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdOverviewRoute = AppProjectsIdOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdPrdRoute = AppProjectsIdPrdRouteImport.update({
  id: '/prd',
  path: '/prd',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdPromptsRoute = AppProjectsIdPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdTasksRoute = AppProjectsIdTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppProjectsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/templates': typeof AppTemplatesRoute
  '/projects/$id': typeof AppProjectsIdRouteWithChildren
  '/projects/baru': typeof AppProjectsBaruRoute
  '/settings/ai': typeof AppSettingsAiRoute
  '/settings/bahasa': typeof AppSettingsBahasaRoute
  '/settings/notifikasi': typeof AppSettingsNotifikasiRoute
  '/settings/profil': typeof AppSettingsProfilRoute
  '/settings/shortcut': typeof AppSettingsShortcutRoute
  '/settings/tampilan': typeof AppSettingsTampilanRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/projects/$id/api': typeof AppProjectsIdApiRoute
  '/projects/$id/architecture': typeof AppProjectsIdArchitectureRoute
  '/projects/$id/canvas': typeof AppProjectsIdCanvasRoute
  '/projects/$id/database': typeof AppProjectsIdDatabaseRoute
  '/projects/$id/export': typeof AppProjectsIdExportRoute
  '/projects/$id/history': typeof AppProjectsIdHistoryRoute
  '/projects/$id/interview': typeof AppProjectsIdInterviewRoute
  '/projects/$id/overview': typeof AppProjectsIdOverviewRoute
  '/projects/$id/prd': typeof AppProjectsIdPrdRoute
  '/projects/$id/prompts': typeof AppProjectsIdPromptsRoute
  '/projects/$id/tasks': typeof AppProjectsIdTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/templates': typeof AppTemplatesRoute
  '/projects/$id': typeof AppProjectsIdRouteWithChildren
  '/projects/baru': typeof AppProjectsBaruRoute
  '/settings/ai': typeof AppSettingsAiRoute
  '/settings/bahasa': typeof AppSettingsBahasaRoute
  '/settings/notifikasi': typeof AppSettingsNotifikasiRoute
  '/settings/profil': typeof AppSettingsProfilRoute
  '/settings/shortcut': typeof AppSettingsShortcutRoute
  '/settings/tampilan': typeof AppSettingsTampilanRoute
  '/projects': typeof AppProjectsIndexRoute
  '/projects/$id/api': typeof AppProjectsIdApiRoute
  '/projects/$id/architecture': typeof AppProjectsIdArchitectureRoute
  '/projects/$id/canvas': typeof AppProjectsIdCanvasRoute
  '/projects/$id/database': typeof AppProjectsIdDatabaseRoute
  '/projects/$id/export': typeof AppProjectsIdExportRoute
  '/projects/$id/history': typeof AppProjectsIdHistoryRoute
  '/projects/$id/interview': typeof AppProjectsIdInterviewRoute
  '/projects/$id/overview': typeof AppProjectsIdOverviewRoute
  '/projects/$id/prd': typeof AppProjectsIdPrdRoute
  '/projects/$id/prompts': typeof AppProjectsIdPromptsRoute
  '/projects/$id/tasks': typeof AppProjectsIdTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/projects/$id': typeof AppProjectsIdRouteWithChildren
  '/_app/projects/baru': typeof AppProjectsBaruRoute
  '/_app/settings/ai': typeof AppSettingsAiRoute
  '/_app/settings/bahasa': typeof AppSettingsBahasaRoute
  '/_app/settings/notifikasi': typeof AppSettingsNotifikasiRoute
  '/_app/settings/profil': typeof AppSettingsProfilRoute
  '/_app/settings/shortcut': typeof AppSettingsShortcutRoute
  '/_app/settings/tampilan': typeof AppSettingsTampilanRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/projects/$id/api': typeof AppProjectsIdApiRoute
  '/_app/projects/$id/architecture': typeof AppProjectsIdArchitectureRoute
  '/_app/projects/$id/canvas': typeof AppProjectsIdCanvasRoute
  '/_app/projects/$id/database': typeof AppProjectsIdDatabaseRoute
  '/_app/projects/$id/export': typeof AppProjectsIdExportRoute
  '/_app/projects/$id/history': typeof AppProjectsIdHistoryRoute
  '/_app/projects/$id/interview': typeof AppProjectsIdInterviewRoute
  '/_app/projects/$id/overview': typeof AppProjectsIdOverviewRoute
  '/_app/projects/$id/prd': typeof AppProjectsIdPrdRoute
  '/_app/projects/$id/prompts': typeof AppProjectsIdPromptsRoute
  '/_app/projects/$id/tasks': typeof AppProjectsIdTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/templates'
    | '/projects/$id'
    | '/projects/baru'
    | '/settings/ai'
    | '/settings/bahasa'
    | '/settings/notifikasi'
    | '/settings/profil'
    | '/settings/shortcut'
    | '/settings/tampilan'
    | '/projects/'
    | '/projects/$id/api'
    | '/projects/$id/architecture'
    | '/projects/$id/canvas'
    | '/projects/$id/database'
    | '/projects/$id/export'
    | '/projects/$id/history'
    | '/projects/$id/interview'
    | '/projects/$id/overview'
    | '/projects/$id/prd'
    | '/projects/$id/prompts'
    | '/projects/$id/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/templates'
    | '/projects/$id'
    | '/projects/baru'
    | '/settings/ai'
    | '/settings/bahasa'
    | '/settings/notifikasi'
    | '/settings/profil'
    | '/settings/shortcut'
    | '/settings/tampilan'
    | '/projects'
    | '/projects/$id/api'
    | '/projects/$id/architecture'
    | '/projects/$id/canvas'
    | '/projects/$id/database'
    | '/projects/$id/export'
    | '/projects/$id/history'
    | '/projects/$id/interview'
    | '/projects/$id/overview'
    | '/projects/$id/prd'
    | '/projects/$id/prompts'
    | '/projects/$id/tasks'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_app/templates'
    | '/_app/projects/$id'
    | '/_app/projects/baru'
    | '/_app/settings/ai'
    | '/_app/settings/bahasa'
    | '/_app/settings/notifikasi'
    | '/_app/settings/profil'
    | '/_app/settings/shortcut'
    | '/_app/settings/tampilan'
    | '/_app/projects/'
    | '/_app/projects/$id/api'
    | '/_app/projects/$id/architecture'
    | '/_app/projects/$id/canvas'
    | '/_app/projects/$id/database'
    | '/_app/projects/$id/export'
    | '/_app/projects/$id/history'
    | '/_app/projects/$id/interview'
    | '/_app/projects/$id/overview'
    | '/_app/projects/$id/prd'
    | '/_app/projects/$id/prompts'
    | '/_app/projects/$id/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/baru': {
      id: '/_app/projects/baru'
      path: '/projects/baru'
      fullPath: '/projects/baru'
      preLoaderRoute: typeof AppProjectsBaruRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/ai': {
      id: '/_app/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AppSettingsAiRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/bahasa': {
      id: '/_app/settings/bahasa'
      path: '/bahasa'
      fullPath: '/settings/bahasa'
      preLoaderRoute: typeof AppSettingsBahasaRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/notifikasi': {
      id: '/_app/settings/notifikasi'
      path: '/notifikasi'
      fullPath: '/settings/notifikasi'
      preLoaderRoute: typeof AppSettingsNotifikasiRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/profil': {
      id: '/_app/settings/profil'
      path: '/profil'
      fullPath: '/settings/profil'
      preLoaderRoute: typeof AppSettingsProfilRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/shortcut': {
      id: '/_app/settings/shortcut'
      path: '/shortcut'
      fullPath: '/settings/shortcut'
      preLoaderRoute: typeof AppSettingsShortcutRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/tampilan': {
      id: '/_app/settings/tampilan'
      path: '/tampilan'
      fullPath: '/settings/tampilan'
      preLoaderRoute: typeof AppSettingsTampilanRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/projects/$id/api': {
      id: '/_app/projects/$id/api'
      path: '/api'
      fullPath: '/projects/$id/api'
      preLoaderRoute: typeof AppProjectsIdApiRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/architecture': {
      id: '/_app/projects/$id/architecture'
      path: '/architecture'
      fullPath: '/projects/$id/architecture'
      preLoaderRoute: typeof AppProjectsIdArchitectureRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/canvas': {
      id: '/_app/projects/$id/canvas'
      path: '/canvas'
      fullPath: '/projects/$id/canvas'
      preLoaderRoute: typeof AppProjectsIdCanvasRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/database': {
      id: '/_app/projects/$id/database'
      path: '/database'
      fullPath: '/projects/$id/database'
      preLoaderRoute: typeof AppProjectsIdDatabaseRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/export': {
      id: '/_app/projects/$id/export'
      path: '/export'
      fullPath: '/projects/$id/export'
      preLoaderRoute: typeof AppProjectsIdExportRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/history': {
      id: '/_app/projects/$id/history'
      path: '/history'
      fullPath: '/projects/$id/history'
      preLoaderRoute: typeof AppProjectsIdHistoryRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/interview': {
      id: '/_app/projects/$id/interview'
      path: '/interview'
      fullPath: '/projects/$id/interview'
      preLoaderRoute: typeof AppProjectsIdInterviewRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/overview': {
      id: '/_app/projects/$id/overview'
      path: '/overview'
      fullPath: '/projects/$id/overview'
      preLoaderRoute: typeof AppProjectsIdOverviewRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/prd': {
      id: '/_app/projects/$id/prd'
      path: '/prd'
      fullPath: '/projects/$id/prd'
      preLoaderRoute: typeof AppProjectsIdPrdRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/prompts': {
      id: '/_app/projects/$id/prompts'
      path: '/prompts'
      fullPath: '/projects/$id/prompts'
      preLoaderRoute: typeof AppProjectsIdPromptsRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/_app/projects/$id/tasks': {
      id: '/_app/projects/$id/tasks'
      path: '/tasks'
      fullPath: '/projects/$id/tasks'
      preLoaderRoute: typeof AppProjectsIdTasksRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAiRoute: typeof AppSettingsAiRoute
  AppSettingsBahasaRoute: typeof AppSettingsBahasaRoute
  AppSettingsNotifikasiRoute: typeof AppSettingsNotifikasiRoute
  AppSettingsProfilRoute: typeof AppSettingsProfilRoute
  AppSettingsShortcutRoute: typeof AppSettingsShortcutRoute
  AppSettingsTampilanRoute: typeof AppSettingsTampilanRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAiRoute: AppSettingsAiRoute,
  AppSettingsBahasaRoute: AppSettingsBahasaRoute,
  AppSettingsNotifikasiRoute: AppSettingsNotifikasiRoute,
  AppSettingsProfilRoute: AppSettingsProfilRoute,
  AppSettingsShortcutRoute: AppSettingsShortcutRoute,
  AppSettingsTampilanRoute: AppSettingsTampilanRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppProjectsIdRouteChildren {
  AppProjectsIdApiRoute: typeof AppProjectsIdApiRoute
  AppProjectsIdArchitectureRoute: typeof AppProjectsIdArchitectureRoute
  AppProjectsIdCanvasRoute: typeof AppProjectsIdCanvasRoute
  AppProjectsIdDatabaseRoute: typeof AppProjectsIdDatabaseRoute
  AppProjectsIdExportRoute: typeof AppProjectsIdExportRoute
  AppProjectsIdHistoryRoute: typeof AppProjectsIdHistoryRoute
  AppProjectsIdInterviewRoute: typeof AppProjectsIdInterviewRoute
  AppProjectsIdOverviewRoute: typeof AppProjectsIdOverviewRoute
  AppProjectsIdPrdRoute: typeof AppProjectsIdPrdRoute
  AppProjectsIdPromptsRoute: typeof AppProjectsIdPromptsRoute
  AppProjectsIdTasksRoute: typeof AppProjectsIdTasksRoute
}

const AppProjectsIdRouteChildren: AppProjectsIdRouteChildren = {
  AppProjectsIdApiRoute: AppProjectsIdApiRoute,
  AppProjectsIdArchitectureRoute: AppProjectsIdArchitectureRoute,
  AppProjectsIdCanvasRoute: AppProjectsIdCanvasRoute,
  AppProjectsIdDatabaseRoute: AppProjectsIdDatabaseRoute,
  AppProjectsIdExportRoute: AppProjectsIdExportRoute,
  AppProjectsIdHistoryRoute: AppProjectsIdHistoryRoute,
  AppProjectsIdInterviewRoute: AppProjectsIdInterviewRoute,
  AppProjectsIdOverviewRoute: AppProjectsIdOverviewRoute,
  AppProjectsIdPrdRoute: AppProjectsIdPrdRoute,
  AppProjectsIdPromptsRoute: AppProjectsIdPromptsRoute,
  AppProjectsIdTasksRoute: AppProjectsIdTasksRoute,
}

const AppProjectsIdRouteWithChildren = AppProjectsIdRoute._addFileChildren(
  AppProjectsIdRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppProjectsIdRoute: typeof AppProjectsIdRouteWithChildren
  AppProjectsBaruRoute: typeof AppProjectsBaruRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTemplatesRoute: AppTemplatesRoute,
  AppProjectsIdRoute: AppProjectsIdRouteWithChildren,
  AppProjectsBaruRoute: AppProjectsBaruRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
